[whisper]
# 자세한 로그 출력 여부
# True: 처리 중 상세 정보 출력, False: 간략한 정보만 출력
verbose = true

# 음성 인식의 무작위성 정도 조절 (0.0~1.0)
# 낮을수록(0에 가까울수록) 더 결정적인 결과 생성(높은 정확도)
# 높을수록 더 다양한 결과 생성(오류 가능성 증가)
temperature = 0.01

# 로그 확률 임계값 설정
# 값이 높을수록 더 많은 구간을 "무음"으로 분류
# 배경 소음이 많은 오디오의 경우 이 값을 낮추면 도움이 됨
logprob_threshold = -1.2

# 무음 임계값 설정 (0.0~1.0)
# 값이 높을수록 더 많은 구간이 "무음"으로 분류됨
# 값이 낮을수록 더 많은 소리가 음성으로 처리됨
no_speech_threshold = 0.6

# 이전 텍스트를 기반으로 다음 텍스트 생성 여부
# True: 이전 텍스트를 고려하여 문맥 유지
# False: 각 세그먼트를 독립적으로 처리
condition_on_previous_text = false

# 초기 프롬프트 설정
# 음성 인식 시작 시 모델에 제공할 문맥 힌트
initial_prompt = "이것은 한국어 회의 녹음이며, 여러 사람이 서로 대화하는 내용입니다. 반복적인 문장이 없이 자연스러운 대화로 진행됩니다."

# 압축 비율 임계값 설정
# 텍스트의 압축 비율이 이 임계값보다 높으면 해당 세그먼트를 무시
# 반복적인 내용이나 장애가 있는 오디오 구간을 걸러내는데 도움
compression_ratio_threshold = 1.8

# GPU 사용 시 FP16(반정밀도) 활성화 여부
# True: GPU에서 더 빠른 처리 가능
# CPU 사용 시 자동으로 false 처리됨
fp16_enabled = true